#server.port = 9090
server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://moonversedb.c3nwzqfeuwbd.us-east-2.rds.amazonaws.com:5432/postgres
    username: moon
    password: moonverse
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

